### ISSUE TITLE
Example github.py doesn't work.

### ISSUE THREAD

**Issue by gbrennon** [jaimegildesagredo/finch#15]
I've just cloned the repo, created a virtualenv, activated it and installed requirements with `pip install -r requiments.txt` and ran `python github.py`

Tornado just throws the following exception:

```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fb9e1809ba8>
Traceback (most recent call last):
  File "/home/gbrennon/Documents/Prog/Python/Tornado/finch_example/finch_repo/env/lib/python2.7/site-packages/tornado/ioloop.py", line 568, in _run_callback
    ret = callback()
  File "/home/gbrennon/Documents/Prog/Python/Tornado/finch_example/finch_repo/env/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/finch/collection.py", line 57, in on_query
    self.on_error(partial(callback, None), response)
  File "build/bdist.linux-x86_64/egg/finch/collection.py", line 41, in on_error
    callback(errors.HTTPError(response.code))
  File "examples/github.py", line 54, in on_repos
    raise error
HTTPError: Forbidden
```

**Comment by jasminprajapati** [comment]
I too getting same error while running this repo code (python github.py). I've met all requirements installed.
